[#43] Github Actions 추가 세팅
f-lab-edu/sool-dam-a pull request #44
Opened 2022-10-10 12:41 UTC by rogarithm

[#43] Github Actions 추가 세팅

## 작업 내용 (Content)
- PR open 이후 최신 커밋이 PR 브랜치에 push될 때도 CI를 실행하도록 github actions 설정을 변경했습니다.

## 기타 사항 (Etc)
- 처음 PR이 열릴 때, PR open과 push 두 조건 모두에 해당되어 CI가 두 번 발생합니다.

## Merge 전 필요 작업 (Checklist before merge)
- [x] PR 제목에 PR과 연관된 이슈 번호를 [이슈 번호] 형식으로 추가

## 리뷰 포인트
- 리뷰어는 리뷰할 때 [Pn 룰](https://github.com/f-lab-edu/sool-dam-a/wiki/프로젝트-문화#코드-리뷰) 을 활용할 수 있습니다.

2022-10-11 13:53 UTC, f-lab-jd requested changes

2022-10-11 13:53 UTC, f-lab-jd commented on .github/workflows/build-on-pr.yml
> +  push:
P3 : 이렇게 설정하시면 PR 의 head branch 가 아닌 branch 의 push event 에도 action 이 수행될텐데요. 혹시 테스트 해보셨나요~? https://github.com/f-lab-edu/sool-dam-a/pull/44/files#diff-9d203c9752e1d33cfea8d5d96c0fe77518a7fe527d28a3ff4cd0e22b58d18112R14 요 값에 `opened` 이 아니라 다른값으로는 어떤게 있을까요~? 아무것도 없는 경우는 어떤 type 의 이벤트에 트리거 될까요~?

2022-10-12 05:10 UTC, rogarithm commented on .github/workflows/build-on-pr.yml
> +  push:
이전에는 다음 두 가지를 테스트했습니다.
- 새로운 PR을 열었을 때 빌드가 실행되는지 확인
- PR 연 후 추가 커밋을 PR할 브랜치에 push했을 때 빌드가 실행되는지 확인

확인해보니 말씀해주신 대로 PR을 열지 않은 상태더라도 PR의 head branch가 아닌 branch 의 push event 에도 action이 수행되고 있었습니다.

opened 이외 type 항목은 이런 것들이 있습니다: assigned, unassigned, labeled, unlabeled, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled

기본 설정 시 pull_request event type이 opened, synchronize, reopened인 경우에 action이 실행됩니다 (원문은 By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened 이며, [이 글](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)을 참고했습니다.)

이 중 synchronize type에 대해 알아보니 PR의 head branch에 새로운 커밋이 push되는 경우를 포함하는 것을 알 수 있었습니다
(Triggered when a pull request's head branch is updated. For example, when the head branch is updated from the base branch, **when new commits are pushed to the head branch**, or when the base branch is changed. 출처는 [여기](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request)입니다.)

push 옵션을 제외하고, pull_request type에 synchronize를 추가해서 테스트했을 때
- push만 했을 때는 action이 실행되지 않는 것을 확인했습니다. 이때 push한 branch는 PR open할 feature branch였습니다. PR이 열리지 않으면 아직 PR head branch가 아니므로 말씀해주신 PR 의 head branch 가 아닌 branch에 해당된다고 판단했습니다.
- 이후 PR을 open한 후에 추가 커밋을 push했을 때 action이 실행되는 것을 확인했습니다.

리뷰해주신 내용과 관련된 github actions 테스트는 [여기](https://github.com/rogarithm/test-gha/issues/7)서 했습니다.

2022-10-12 11:05 UTC, f-lab-jd approved these changes

2022-10-13 00:28 UTC, dev-seokho commented
P2 : build 할 때, application.yml에 있는 mysql env 들에 대해서 깃헙액션에도 적용해주어야 DB에 관련된 테스트코드가 실행될 것 같은데 제가 고려하고 있는게 맞는지 궁금합니다!!

2022-10-17 07:55 UTC, merged