[#18] 제품 조회 기능
f-lab-edu/sool-dam-a pull request #45
Opened 2022-10-12 22:44 UTC by dev-seokho

# [#18] 제품 조회 기능

## 작업 내용 (Content)
- 제품 조회 기능 개발 (Feat. 페이지네이션)
- 전역적인 Exception 처리를 위해서 ControllerAdvice와 ExceptionHandler를 활용, 폴더 구조 지정
- Response의 통일성을 위해서 BasicResponse 개발 및 활용
- MockMvc를 활용해서 Controller Layer에 대한 테스트 개발
- Mokito를 활용해서 Service Layer에 대한 테스트 개발

## 기타 사항 (Etc)
- 

## Merge 전 필요 작업 (Checklist before merge)
- [ ] PR 제목에 PR과 연관된 이슈 번호를 [이슈 번호] 형식으로 추가

## 리뷰 포인트
- 리뷰어는 리뷰할 때 [Pn 룰](https://github.com/f-lab-edu/sool-dam-a/wiki/프로젝트-문화#코드-리뷰) 을 활용할 수 있습니다.

2022-10-12 22:51 UTC, dev-seokho commented
<img width="911" alt="image" src="https://user-images.githubusercontent.com/56547148/195462200-84511ef1-e989-4cc3-8de0-7d16924946c3.png">

2022-10-15 03:19 UTC, f-lab-jd requested changes
@dev-seokho 고생하셨습니다~~! 
리뷰드린 내용 확인 부탁드립니다 ㅎㅎ (cc. @rogarithm)

2022-10-15 03:19 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/product/dto/response/ProductsResponse.java
> +    private List<Product> products;
P3: Product DTO 에 Entity 가 그대로 포함되었을때 어떤 장단점이 있을까요~? 
(cc. @rogarithm)

2022-10-15 03:19 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/exception/GlobalExceptionHandler.java
> +@Slf4j 어노테이션은 Lombok 어노테이션중 하나로, 좀 더 편리하게 로그를 찍을 수 있게 도와줍니다.
P3: @dev-seokho 작성해주신 내용도 사실이지만.. ㅎㅎ   
어떤 원리로 동작하는지 좀 더 구체적인 내용이면 더 좋을 것 같습니다.

2022-10-15 03:19 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/exception/GlobalExceptionHandler.java
> +@ControllerAdvice 어노테이션은 컨트롤러에서 쓰이는 공통 기능들을 모듈화하여 전역적으로 쓰게 도와줍니다.
P3: @dev-seokho 마찬가지로, `ControllerAdvice` 는 무엇이고 어떤 동작원리로 동작하는것일까요? (cc. @rogarithm)

2022-10-15 03:19 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/exception/GlobalExceptionHandler.java
> +        log.error(e.getMessage(), e);
P3: @dev-seokho `error` 로그를 남기는 기준은 무엇일까요~? log level 엔 어떤값들이 있을까요~? 
4xx (클라이언트) 에러인데, 서버에 error 로그를 남기는게 좋을지, 
어떤 기준을 만들면 좋을지 @rogarithm 님과 한번 이야기 한 후에 정책을 정해보면 좋을 것 같습니다.

2022-10-15 03:19 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/response/BasicResponse.java
> +public class BasicResponse<T> {
P3: @rogarithm `BasicResponse` 라는 Response DTO 의 Wrapper 클래스를 만드신 이유가 있을까요~? 
어떤 장단점이 있을까요~?

2022-10-15 03:19 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/api/ProductApiTest.java
> +@AutoConfigureMockMvc
P2: `@WebMvcTest` 와는 무슨 차이점이 있을까요? Controller Layer 에 대한 단위 테스트를 의도하신게 맞으실까요~? 
(cc. @rogarithm)

2022-10-15 03:19 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/api/ProductApiTest.java
> +        this.mockMvc.perform(get("/products")).andExpect(status().isOk());
P5 : https://github.com/f-lab-edu/sool-dam-a/pull/45/files#diff-fa6991db5e57382feae0826e6309aa0c26acf15eaab8a39b5e3c6cb5b2a4a41eR29-R32 와 개행 일관성이 맞지 않아 가독성을 해치는것 같습니다 ㅎㅎ

2022-10-15 03:19 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/service/ProductServiceTest.java
> +        }
P5 : 임의의 테스트 데이터를 만들기 위한 목적으로 https://github.com/j-easy/easy-random 이나 https://github.com/AutoParams/AutoParams 를 도입하는것도 고려해보시면 좋을 것 같습니다. (cc. @rogarithm)

2022-10-15 03:19 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/service/ProductServiceTest.java
> +        assertEquals(limit - offset, productsResponse.getProducts().size());
P5 : input 과 output 의 size 만 같다고 테스트가 성공했다고 볼 수 있을까요~?

2022-10-15 03:24 UTC, f-lab-jd commented
@dev-seokho  https://github.com/f-lab-edu/sool-dam-a/pull/45#issuecomment-1276811904 질문에 대해 답변드리자면, 
Github action에서 빌드 수행시에 환경변수를 주입해주면, build 가 성공할 수 있을까요~?
성공하려면 어떤 변수를 넣어주어야할까요~? 아니면 Test 를 위한 환경을 구성할 수 있는 방법은 없을까요~? 
이 부분은 별도 이슈로 만들어서 @rogarithm 과 함께 고민해주시면 좋을 것 같습니다!
고민해보신 해결방안을 Slack 이나 이슈 안에 남겨주시면, 해당 내용 기반으로 같이 이야기 나누어보시죠~!

2022-10-16 12:28 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/product/dao/ProductMapper.java
> +    List<Product> selectProducts(@Param("offset") Integer offset, @Param("limit") Integer limit);
술담아 사이트에서는 첫화면에 모든 상품이 다 보여지는 API를 사용합니다. 사실 내부적으로는 Where 절에서 defualt로 All 을 사용하고, product_category_id를 사용해서 카테고리별로도 가져올 수 있게 구현되있을 것이라고 느껴지는데요, 고민하긴 했는데 서브기능이라고 생각하고 일단 조건없이 전체 조회 API를 만들었습니다. Where절도 추가를 해서 모든 상품을 가져올수도 있으면서 동시에 product_category_id를 활용해서 카테고리별 상품도 가져올 수 있게 구현해주는게 좋을까요?!

2022-10-16 12:31 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/global/response/BasicResponse.java
> +public class BasicResponse<T> {
@f-lab-jd  제가 느낀 장점은, Response 코드 스타일과 JSON 스타일을 일관성있게 맞춰주기 때문에 만들었습니다. 단점으로 생각나는 것은 관리에 리소스 소모? 가 있을수도 있다는 생각이 드는데, JD님이 느끼시는 단점이 있으실까요?!

2022-10-16 12:36 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/product/api/ProductApi.java
> +        return ResponseEntity.status(HttpStatus.OK).body(BasicResponse.success(productsResponse));
해당 방법으로 구현하는 것도 알고 있었지만, 이렇게 표현한 이유는 사실 global/exception/GlobalExceptionHandler 에서 
`return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(BasicResponse.fail(e.getMessage()));`로 구현을 해놓아서 일관성을 맞춰주기위한 의도였는데, 컨트롤러 쪽에서는 그냥 .ok로 표현해도 괜찮겠죠?

2022-10-16 12:37 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/product/api/ProductApi.java
> +        }
넵 :)

2022-10-16 12:37 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/product/dao/ProductMapper.java
> +public interface ProductMapper {
@f-lab-jd 구현하지 않은 이유는 없었는데, 구현해보도록 하겠습니다! :)

2022-10-16 12:39 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/global/exception/GlobalExceptionHandler.java
> +@Slf4j 어노테이션은 Lombok 어노테이션중 하나로, 좀 더 편리하게 로그를 찍을 수 있게 도와줍니다.
넵 :) 주석 수정해보겠습니다.

2022-10-16 12:40 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/global/exception/GlobalExceptionHandler.java
> +@ControllerAdvice 어노테이션은 컨트롤러에서 쓰이는 공통 기능들을 모듈화하여 전역적으로 쓰게 도와줍니다.
주석에 좀 더 추가해보도록 할게요!

2022-10-16 12:40 UTC, dev-seokho commented on src/test/java/com/flab/sooldama/domain/user/api/ProductApiTest.java
> +        this.mockMvc.perform(get("/products")).andExpect(status().isOk());
개행 수정하도록 하겠습니다 !

2022-10-16 12:40 UTC, dev-seokho commented on src/test/java/com/flab/sooldama/domain/user/service/ProductServiceTest.java
> +        }
넵 고려해보겠습니다

2022-10-16 12:41 UTC, dev-seokho commented on src/test/java/com/flab/sooldama/domain/user/service/ProductServiceTest.java
> +        assertEquals(limit - offset, productsResponse.getProducts().size());
@f-lab-jd 혹시 더 고려해보아야할 테스트가 어떤게 있을까요!?!

2022-10-16 12:48 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/global/exception/GlobalExceptionHandler.java
> +        log.error(e.getMessage(), e);
서비스의 동작 상태 파악과, 장애 파악과 알람으로 인해서 error로그를 남겨야합니다. 전 회사에서 개발 때에는 라라벨 PSR-3 표준을 따르는 로그 단계에서(로그 레벨이 8가지였습니다.) error 로그레벨이 크리티컬 이상이라면 slack으로 알람이 올 수 있도록 운영했었습니다. 사이드프로젝트 수준에서 error로그를 남긴 것은 두가지 이유중 서비스의 **동작 상태 파악** 으로 인해서인데요, 개발하고, 실제로 Exception에 걸리는 잘못된 요청을 일부러 냈을 때, 의도대로 동작했는지 로그를 보며 확인해보기 위해서 4xx번대 에러이지만 error log를 삽입했습니다.
slf4j 에서는 로그레벨이 다음과 같습니다! 

```
1. trace : debug보다 세분화된 정보
2. debug : 디버깅하는데 유용한 세분화된 정보
3. info : 진행상황 같은 일반 정보
4. warn : 오류는 아니지만 잠재적인 오류 원인이 될 수 있는 경고성 정보
5. error : 요청을 처리하는 중 문제가 발생한 오류 정보
```

2022-10-16 19:22 UTC, dev-seokho commented on src/test/java/com/flab/sooldama/domain/user/service/ProductServiceTest.java
> +        }
@f-lab-jd  easy-random이 사용사례도 많고 간편한 것 같아서 직접 코드에 적용해보았습니다.
일단 Product 객체에 대해서 easy random을 사용한다면, id, createdAt, updatedAt, deletedAt은 제외해야 하고 productCategoryId는 범위가 1~5 여야 합니다. 실제로 코드를 작성해보았는데,
<img width="560" alt="image" src="https://user-images.githubusercontent.com/56547148/196053801-15bbd156-79ed-4490-a3f1-7391a36a51c7.png">
이러한 상황과 같이 생각보다 코드가 길어지는 것 같습니다. (심지어 아직 productCategoryId는 범위가 1~5까지라는 설정은 코드 작성하지 않았습니다.) 
현 상황에서 easy-random을 고려하는 것이, 데이터가 적고 테스트할 것이 적은 상태에서 더 많은 리소스를 쓰게 되는 것이 아닌지 궁금합니다!! 하지만 확실히 제외할 것이 많이 없거나, 테스트용 객체가 List라면 easy-random이 코드 줄 수를 많이 낮춰준다고 느껴집니다.

P5라서 꼭 적용해야 하는 것은 아니라고 느껴지는데 JD님은 테스트 코드를 작성하실 때 easy-random을 적극 활용하시는 편이신가요!?

2022-10-16 21:24 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/product/api/ProductApi.java
> +        }
@f-lab-jd  @Validated 와 @Min을 활용해서 수정 완료했습니다. @Validated 가 내밷는 ConstraintViolationException에 대해서도 ExceptionHandler에서 일괄적으로 처리할 수 있도록 했습니다. :)

2022-10-17 09:45 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/product/dto/response/ProductsResponse.java
> +    private List<Product> products;
이것에 대해서 조사해보았는데, 마땅히 와닿는 레퍼런스를 찾지 못했습니다. 혹시 좋은 키워드나 글이 있을까요?

2022-10-17 10:11 UTC, dev-seokho commented on src/test/java/com/flab/sooldama/domain/user/api/ProductApiTest.java
> +@AutoConfigureMockMvc
제가 구현한 @SpingBootTest + @AutoConfigureMockMvc는 프로젝트 내부에 있는 스프링 빈을 모두 등록하여서 테스트에 필요한 의존성들을 추가합니다. Controller Layer에 대한 단위 테스트를 의도한게 아닌 Spring Framework를 사용한 API Feature가 정확히 동장하는지에 대한 통합테스트를 ControllerTest에서 진행했습니다. 이에 대한 장점은 애플리케이션의 설정과 Bean을 모두 로드하기 떄문에 운영환경과 가장 유사한 기능테스트이자 통합테스가 됩니다. 하지만 단점은 테스트 단위가 API Flow 전체이기 때문에 디버깅이 까다롭고, 모든 Bean을 로드하기 떄문에 시간이 오래걸립니다.

말씀해준신 @WebMvcTest는 컨트롤러가 예상대로 작동하는지 Web Layer만 로드하는 어노테이션이며, 특정 항목들만 스캔하도록 제한되어 @AutoConfigureMockMvc 테스트보다 가볍고 빠른 테스트가 가능합니다. 즉 통합테스트에 가까운 @AutoConfigureMockMvc와는 다르게 유닛테스트에 가깝습니다. 하지만 단점으로는 Mock을 사용한 테스트 이기 때문에, 실제 환경과 동일하지 않습니다.

2022-10-17 14:51 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/product/api/ProductApi.java
> +        return ResponseEntity.status(HttpStatus.OK).body(BasicResponse.success(productsResponse));
@dev-seokho 일관성을 맞추려는 의도와 시도는 아주 좋습니다 👍 
저는 `ResponseEntity` 에서 제공해주는 편의 메소드를 이용하는것이 일관성을 깨뜨린다라고 생각이 들지는 않는데요. ㅎㅎ
일관성이 목적이셨다면, 마찬가지로, @rogarithm 님과 함께 논의해서 결정하면 좋을 것 같습니다.

2022-10-17 15:03 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/product/dao/ProductMapper.java
> +    List<Product> selectProducts(@Param("offset") Integer offset, @Param("limit") Integer limit);
음 설계하신 테이블 구조에 의하면 삭제된 상품도 불러오지 않을까요~? 별개로 말씀하신 category_id 별로 분류하는쿼리도 필요할 수 있겠네요 ㅎㅎ product 테이블에 대해 운영을 할만큼 상세히 설계된게 아니지만, WHERE 조건 없는 select 쿼리가 사용자 요청에 의해 호출이 될 수 있다면, 사이드이펙트가 생길우려가 있기도 합니다.

2022-10-17 15:09 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/product/dto/response/ProductsResponse.java
> +    private List<Product> products;
@dev-seokho @rogarithm  음 결국에는 Entity 클래스가 DTO 클래스 역할`도` 하게 될텐데요. Entity 클래스와  DTO 클래스의 차이점과 공통점에 대해 고민해보시고, 유연하게 확장할 수 있을지, 객체지향 원칙 SRP 에도 부합한지(부합하게 사용할수 있을지) 등을 고민해보시면 좋을 것 같습니다.

2022-10-17 15:17 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/response/BasicResponse.java
> +public class BasicResponse<T> {
이미 서버와 클라이언트 통신을 위해 잘 설계된 `http` 라는 훌륭한 프로토콜을 사용하고 있기에..
(현재 작성하신 BasicResponse 클래스를 보았을때) wrapping 한다라는 의미만 있고, 장점이 없는게 단점이라고 생각합니다 ㅎㅎ
success 여부는 http status code 로 클라이언트가 알 수 있고, 응답 데이터는 data 라는 필드에 감싼다라는 의미밖에 없지 않나요..?

2022-10-17 15:24 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/product/dao/ProductMapper.java
> +    List<Product> selectProducts(@Param("offset") Integer offset, @Param("limit") Integer limit);
@f-lab-jd 말씀해주신데로 deleted_at도 확인할 수 있는 쿼리로 변경을 해야겠네요!

또한 만약에 category_id 별로 분류하는 것이 필요하다면 API를 다음과 같이 분류할 수 있을 것 같습니다.
1. URL 파라미터를 이용한다 -> `[GET] products/{product_category_id}?offset={offset}&limit={limit}`
2. 쿼리스트링을 이용한다 -> `[GET] products?type={product_category_id}&offset={offset}&limit={limit}`
타입분류이고, default 값은 전체 상품을 가져온다 라는 생각으로 접근했을 때는 2번 방법이 좋을 것 같은데요, 두가지 방법 모두 결국 Frontend가 product_category에 대한 정보를 알고 있어야만, id나 다른 정보를 통해서 원하는 정보를 가져올 수 있다는 생각이 듭니다.

그렇다면 이를 위해서 product_category에 대한 정보를 알려주는 API도 함께 구현해야 할까요? 아니면 일단 생략하는게 맞을까요?

2022-10-17 15:25 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/api/ProductApiTest.java
> +@AutoConfigureMockMvc
잘 이해하고 계십니다. (정답이 있는 내용은 아닙니다) 통합테스트가 많이 있을때 vs 단위테스트가 많이 있을때 개발자에게 주는 장단점이 무엇일지 한번 고민해보시고, 저희 프로젝트 안에서 통합테스트와 단위테스트를 작성하는 기준을 세우면 좋을 것 같습니다. 패키지부터 명확하게 분리해도 좋겠죠 ㅎㅎ (cc. @rogarithm)

2022-10-17 15:25 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/global/response/BasicResponse.java
> +public class BasicResponse<T> {
말씀해주신걸 기반으로 생각해보니 오히려 Wrapping이 장점이 없다는게 정말 단점이 될 수도 있겠네요 !! 수정해보겠습니다 :)

2022-10-17 15:38 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/service/ProductServiceTest.java
> +        }
실제 운영시 사용이 되는 소스코드만큼, 테스트코드도 가독성과 일관성을 고려하여 확장성있게 잘 관리되어야 합니다. 유지보수가 어려운 테스트 코드는 머지않아 끔찍한 레거시 코드가 될 확률이 높습니다. 프로젝트가 커질 수록 테스트코드도 많아질텐데요. `임의의 테스트 데이터를 만드는 로직` 을 잘 유지보수할 수 있게 도움을 주는 라이브러리라고 생각해서 추천드렸습니다.  (저는 위에 말씀드린 두 라이브러리를 실무에서 잘 활용한 경험이 있습니다 ㅎㅎ)  이게 가독성을 오히려 해치고 리소스 낭비가 될 수도 있다고 생각하는데요. 단, 위에 말씀드렸던 내용을 고려해서 테스트코드 유지보수를 위해 신경을 잘 써주셔야합니다.

>  일단 Product 객체에 대해서 easy random을 사용한다면, id, createdAt, updatedAt, deletedAt은 제외해야 하고 productCategoryId는 범위가 1 - 5 여야 합니다. 실제로 코드를 작성해보았는데,

테스트코드는 성공하는 케이스, 예상하는 케이스에서만 성공해야하는것이 아니라 실패하는 케이스, 예상 밖의 케이스에 대해서도 커버할 수 있어야합니다. 이러한 관점에서 위에 말씀하신 한가지 케이스만 존재하지는 않을겁니다 ㅎㅎ

2022-10-17 15:41 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/service/ProductServiceTest.java
> +        assertEquals(limit - offset, productsResponse.getProducts().size());
size 만 검사하는것은 석호님이 짐작하는 결과가 개입된것은 아닐까요? ㅎㅎ
productService 의 getProducts 메소드가 하는 역할을 생각해보시고, 어떤 내용을 테스트해야할지 다시 고민해보시면 좋을 것 같습니다.

2022-10-17 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/product/api/ProductApi.java
> +또한 @Validated 어노테이션은 자바 진영 스펙인 @Valid와 달리 스프링 프레임워크에서 제공하는 어노테이션 기능입니다.
👍 
@rogarithm 님도 각 어노테이션이 왜 사용되었는지 반드시 숙지하고 넘어가셔야합니닷

2022-10-17 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/product/dao/ProductMapper.java
> +    List<Product> selectProducts(@Param("offset") Integer offset, @Param("limit") Integer limit);
1번의 경우에는 잘못 설계된 API 가 아닐까요..? ㅎㅎ 
자원을 올바르게 표현한 API 가 아니기도하고, `/products/{productId}` 가 이미 해당 URI 는 선점하고 있을겁니다. 
그리고 2번을했을때에 type 이라는 쿼리스트링이 아닌 category-id  나 categoryId 가 더 명시적이지 않을까요~? 

> 그렇다면 이를 위해서 product_category에 대한 정보를 알려주는 API도 함께 구현해야 할까요? 아니면 일단 생략하는게 맞을까요?

설계하기 나름이겠지만, 말씀하신대로 유효한 category 리스트를 내려주는 API 가 있으면 좋을 것 같습니다.

2022-10-17 15:52 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/response/FailResponse.java
> +public class FailResponse<T> {
@dev-seokho `FailResponse` 클래스를 설계하신 이유는 무엇일까요~? 반드시 필요할까요?! ㅎㅎ 
`message` 가 Generic Type 인 이유도 궁금합니다!

2022-10-17 16:06 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/global/response/FailResponse.java
> +public class FailResponse<T> {
@f-lab-jd  GlobalExceptionHandler에서 실패한 request들에 대해서 실패한 에러 메세지와 함께 JSON 형태로 Response를 하고 싶었습니다.
그냥 response를 e.messege를 사용해서 response 해주게 되면 String으로 반환이 되어서, 이를 DTO 형태로 변환시켜서 JSON 형태로 바꾸고자 설계했습니다. 다른 좋은 방법이 있을까요? ㅠㅠ
messege가 generic type인 이유는 사실 말씀드린것 처럼 e.message가 String 타입으로 반환되어서 사실상 <T> 타입이 아닌 String만 들어온다는 사실을 알고 있긴 한데,, 아무래도 스프링진영에서 핸들링이 처음이다 보니 혹시라도 String 타입 말고 다른 타입이 들어오게 되는 일도 있지 않을까..? 라는 생각에 일단 제네릭으로 처리를 했던 것 같습니다.

2022-10-17 16:09 UTC, dev-seokho commented
> @dev-seokho 아 그리고 혹시 google java coding convention 이 잘 적용된건가요..!?

인텔리제이에서 지원하는 google-java-format 을 사용하고 있는데, 계속 깨지는 것으로 보아서 다른 조치가 필요할 것 같습니다..
한번 알아보겠습니다!!

2022-10-17 16:10 UTC, dev-seokho commented
> @f-lab-jd 설계하기 나름이겠지만, 말씀하신대로 유효한 category 리스트를 내려주는 API 가 있으면 좋을 것 같습니다.
이것은 다음 PR 작업으로 생각해두겠습니다!

2022-10-17 18:51 UTC, dev-seokho commented
@f-lab-jd 
categoryId를 사용할 수 있도록 구현해 보았으며, 테스트 코드도 보완하고 작성해 보았습니다. :) 또한 deleted 된 상품을 제외했습니다.
좀 더 보완할 부분에 대해서 확인해주시면 감사하겠습니다 ㅎㅎ

2022-10-18 14:35 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/response/FailResponse.java
> +public class FailResponse<T> {
아래 내용에 대해 한번 생각해보시고 답변해보시면 좋을 것 같습니다. 
1. 예외가 발생한 경우 exception 의 message 를 응답할 필요가 있을까요? 있다면, message 만 응답하는 이유가 있을까요? 다른 데이터는 필요가 없을까요~? 
2. `message` 라는 필드에 String 이 아닌 다른 타입의 데이터가 들어온다고 했을때, 클라이언트는 일관된 답변을 받을 수 있을까요? (스프링 진영과는 무관합니다)
3.  1,2를 종합했을때 `FailResponse` 라는 실패 응답을 래핑하는 클래스가 반드시 필요할까요~? 오히려 기능을 제한하는것은 아닐까요?! 
4. API 응답을 위한 래핑 클래스는 어떤 경우에 사용하는게 좋을까요?

2022-10-18 14:36 UTC, f-lab-jd commented
@dev-seokho  google-java-format  관련해서는 메시지로 말씀드린 formatter 를 업로드하고 변경사항은 `.editorconfig` 에 반영하는 방향으로 진행하심 좋을 것 같습니다!

2022-10-18 14:47 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/product/api/ProductApi.java
> +                        : productService.getProductsByCategoryId(offset, limit, categoryId);
@dev-seokho QueryString 조건이 늘어날수록 (ex. 날짜 검색 조건 추가) 아래 처리를 중복해서 해줘야할텐데요. 
1. Controller Layer 에서 분기문 추가
2. Service Layer 에 메소드 추가
3. Repository 및 Mapper(쿼리) 추가

(QueryString 조건에 대해서만) 이를 3번에만 처리할 수 있는 방법은 없을까요? 
`mybatis  동적 쿼리` 에 대해 한번 알아보시고, 이슈를 만드셔서 다음 PR 에 반영해보시면 좋을 것 같습니다.

2022-10-19 08:43 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/global/response/FailResponse.java
> +public class FailResponse<T> {
1. message를 응답할 필요가 있다고 생각합니다. 예를들어서 ConstraintViolationException의 특성상 Validated에 대한 예외인데, 어떤 유효성 검증 실패 때문에 Validated를 통과하지 못했는지 메세지가 없다면 클라이언트에서 알 수 없습니다. 그렇기 때문에 메세지를 담아주어야 클라이언트측에서 이러이러한 부분에서 예외가 낫구나 라고 생각하고, 수정할 수 있습니다. 만약 다른 데이터가 필요하다면, 어떤 예외인지 (`ConstraintViolationException`) 함께 담아 주는 것도 좋다고 생각합니다.
2. message는 사실 무조건 String이 되어야 맞다고 봅니다. 그래야 클라이언트가 이를 통해서 일관적인 답변도 받을 수 있고, 더불어 혹시라도 이 message를 그대로 사용하기에도 명확해질 수 있다고 생각합니다.
3. 제 생각에는 FailResponse 실패 응답을 래핑하는 클래스가 필요하다고 생각합니다. 기능을 제한할 수는 있지만, Exception시에 클라이언트에게 피드백과, 어떤 Exception이 발생한 것인지 알려주기 위해서 입니다. 혹시라도 래핑 클래스가 아닌 다른 방법으로 이를 처리할 수 있나요? 만약 다른 방법으로 동일한 아웃풋을 낼 수 있는 더 좋은 방법이 있다면 알려주세요!!
4. 일관적이고 공통적인 데이터를 받아야한다면, 그를 위한 래핑 클래스를 사용할 수 있을 것 같습니다!

결론적으로, 해당 FailResponse에 Message만 담는 것이 아닌 Exception 종류도 데이터에 포함하고, message를 generic type이 아닌 String으로 변환하면 사용해도 좋지 않을까요!?

2022-10-19 08:46 UTC, dev-seokho commented
> @dev-seokho google-java-format 관련해서는 메시지로 말씀드린 formatter 를 업로드하고 변경사항은 `.editorconfig` 에 반영하는 방향으로 진행하심 좋을 것 같습니다!

formatter를 업로드 하는 것도 해당 PR이 아닌 다음 PR로 적용하겠습니다 :)

2022-10-20 05:21 UTC, rogarithm approved these changes
@f-lab-jd 말씀해주신대로 어노테이션 용례 숙지하고 넘어가겠습니다.
@dev-seokho P4: 브랜치 이름 정책을 정하면 어떨까요. 이전 PR까지 스네이크 케이스 형식을 사용했어서 통일성을 유지하면 좋을 것 같아서요.

2022-10-20 13:43 UTC, dev-seokho commented
> @f-lab-jd 말씀해주신대로 어노테이션 용례 숙지하고 넘어가겠습니다. @dev-seokho P4: 브랜치 이름 정책을 정하면 어떨까요. 이전 PR까지 스네이크 케이스 형식을 사용했어서 통일성을 유지하면 좋을 것 같아서요.

넵 다음 커밋부터 스네이크 케이스 적용하겠습니다 :)

2022-10-21 15:15 UTC, f-lab-jd approved these changes
고생하셨습니다~! 👍

2022-10-21 19:30 UTC, merged