[#3] 회원가입 기능
f-lab-edu/sool-dam-a pull request #46
Opened 2022-10-16 09:46 UTC by rogarithm

[#3] 회원가입 기능

## 작업 내용 (Content)
- 회원가입 기능 및 테스트 구현

## 기타 사항 (Etc)
- UserApi 클래스의 joinUser 메소드 반환값으로 JoinUserResponse가 필요할까 고민을 했습니다. 필요할 경우 get api로 가져올 수 있어 중복인 것 같아 상태 코드만 반환하도록 구현했습니다.
- UserApi와 UserService 클래스에 대한 테스트를 먼저 @SpringBootTest가 붙은 통합 테스트로 구현하고 단위 테스트 방식으로 바꾸려고 했는데, 잘 되지 않아 UserApi 테스트만 단위 테스트 방식으로 변경했습니다.

## Merge 전 필요 작업 (Checklist before merge)
- [x] PR 제목에 PR과 연관된 이슈 번호를 [이슈 번호] 형식으로 추가

## 리뷰 포인트
- 리뷰어는 리뷰할 때 [Pn 룰](https://github.com/f-lab-edu/sool-dam-a/wiki/프로젝트-문화#코드-리뷰) 을 활용할 수 있습니다.

2022-10-16 12:09 UTC, dev-seokho requested changes

2022-10-16 12:09 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +        userMapper.insertUser(request.toUser());
P1 : 이 로직만 봤을때는 아무런 암호화 작업 없이 password가 그대로 DB에 들어간다고 보여지는데요, 사용자의 비밀번호가 암호화가 되지 않고 DB에 그대로 password가 입력되는 것은 절대적으로 피해야되는 상황으로 알고 있습니다. 이에대해서 어떻게 생각하시나요?!

2022-10-16 12:09 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/user/dto/request/JoinUserRequest.java
>  public class JoinUserRequest {
P1 : JoinUserRequest 에서 @Valid를 사용한 유효성 검사 로직들이 필요 할 것 같습니다.
예를 들어서,
Email이 Email 포맷이 아닌 이상한 포맷일 경우, 비밀번호는 특수문자와 대소문자를 포함해야한다거나( 이럴 때는 regex를 사용해 볼 수 있을 것 같습니다.), 값들이 비어있다거나(UserApi에서 처리했던 로직을 이곳에서 @NotNull을 통해서 구현해볼 수 있을 것 같습니다.) , 주류를 다루다보니, 성인인증이 완료돼었는지 확인하는 로직이라던가, 하는 유효성 검사들이 필요할 것 같습니다. 지금같은 경우에는 아무런 제약조건 없이 회원가입이 가능한 상황이라고 생각됩니다.

2022-10-16 12:20 UTC, dev-seokho commented
코드를 읽으면서 생각한 것인데, 저희가 전역적인 Response처리와 Exception 처리, Validation 처리에 대해서 코드 스타일이 통일이 되지 않았다고 느낍니다. 기능 구현 완료 후에 페어프로그래밍으로 리팩토링을 하면서 전체적인 틀에 대해서 정해보는 것도 좋다고 느껴지네요. :) 처음 코드스타일을 맞추는데 페어프로그래밍이 굉장히 효과적이라고 느낍니다. 

추가적으로, API Doc에 대해서도 생각하고 있는데요 스웨거나 포스트맨을 활용해 볼 수 있다고 느껴집니다. 두가지 다 사용해본 제 경우엔 저희같이 사이드프로젝트를 하는 상황이라면 포스트맨이 좀 더 나을거라고 생각을 합니다. 만들기 간단하고, 저희끼리 보기 간편하니까요! 이 생각에 대해서 어떻게 생각하시나요?! @f-lab-jd @rogarithm

2022-10-16 17:40 UTC, dev-seokho commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    (#{id}, #{email}, #{password}, #{name}, #{phoneNumber}, #{nickname}, #{isAdult}, #{createdAt},
P2: id 같은 경우에는 자동으로 증가하는 값이 설정되는데 직접 쿼리에 넣어주신 이유가 궁금합니다! 또한 추가적으로, updated_at과 deleted_at이 회원 생성 시점에 필요한 이유도 궁금합니다!

2022-10-16 17:40 UTC, dev-seokho commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    (#{id}, #{email}, #{password}, #{name}, #{phoneNumber}, #{nickname}, #{isAdult}, #{createdAt},
P1: 추가적으로 DB관련해서 말씀드리고 싶은게 있습니다. created_at이라는 컬럼은 사실 회원가입이 되는 시점에, DB에서 현재 시각으로 자동설정되도록 만들어 주어야한다고 생각합니다. 하지만 저희는 DB 모델링 시에, created_at에 대하여 `현재 시점으로 생성된다`라는 default 값을 만들어주지 않았었고, 아마 DDL에 반영이 되지 않아서 created_at값을 직접 전달해주지 않는다면 SQL Exception이 날 것으로 예상됩니다.
만약 flyway를 도입했다면, db 수정건에 대해서 pr을 날렸겠지만, 아직 적용 전이기 때문에 create_at에 now()값을 넣어주셔야할 것 같습니다. 디비다이어그램.io에서 제가 일괄적으로 이부분에 대해서 수정했습니다.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/56547148/196049674-e0aac93d-f4dd-49c6-986c-c65c783133dc.png">

또한 이를 적용하신다면, created_at도 위에 말한 id와 같은 상황으로, 자동으로 디비에서 insert 시점에 시간을 넣어주기 때문에 쿼리에 포함하지 않아도 될 것 같습니다!

2022-10-16 17:40 UTC, dev-seokho commented on src/test/java/com/flab/sooldama/domain/user/api/UserApiTest.java
> +                JoinUserRequest.builder()
P1: UserMapper.xml에 남긴 의문들 처럼 직접 id값을 넣어주는것이 의문이고, createdAt을 DB가 insert 시점에 해당시점으로 자동설정되도록 변환시켜주어야 할 것 같습니다. 이 부분 외에도 JoinUserRequest에서 builder를 사용할때 현 상황이 중복적으로 발생돼있는 것 같아서 이부분도 고려해보아햘 것 같습니다!!

2022-10-17 07:50 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +    public void joinUser(@RequestBody JoinUserRequest request) throws Exception {
말씀하신 내용이 잘 이해가 안가서요. 'joinUser 메서드의 입력이 null이면 안된다' 라는 유효성 검증을 `@NotNull` 어노테이션으로 한다는 의미로 보면 될까요?

2022-10-17 07:50 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +            throw new Exception("필수 정보 누락");
넵, 저도 유효하지 않은 입력일 경우 다른 http 상태 코드를 반환해야 할 것 같다고 생각합니다. 현재 구현은 `@ResponseStatus(HttpStatus.CREATED)`로 반환할 http 상태 코드를 주고 있는데요. 말씀해주신 상황에 다른 상태 코드를 반환할 수 있도록 하려면 어떻게 해야 할지 찾아봤는데 잘 찾지 못해서요. 일단 이 메소드에 대한 테스트를 통과할 수 있게까지만 구현하고 리뷰 과정에서 고치는 것이 좋겠다고 생각했습니다.

2022-10-17 07:50 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +    public JoinUserResponse findUserById(Long id) {
넵, 저도 findUserById 메소드가 어느 레이어까지 필요할 것인가? 하는 고민을 했었습니다. 저는 회원가입하는 과정에 필요할만한 상황이 떠오르지 않았는데요. 말씀해주신 내용을 보니 활용할 수 있을 것 같네요ㅎㅎ

2022-10-17 07:50 UTC, rogarithm commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    (#{id}, #{email}, #{password}, #{name}, #{phoneNumber}, #{nickname}, #{isAdult}, #{createdAt},
auto increment가 설정된 열일 때 쿼리에 넣어주지 않아도 된다는 걸 모르고 있었습니다. 이 부분은 수정하는 것 외에도 관련 사항을 조금 더 알아보고 댓글로 남겨보도록 하겠습니다.

2022-10-17 07:50 UTC, rogarithm commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    (#{id}, #{email}, #{password}, #{name}, #{phoneNumber}, #{nickname}, #{isAdult}, #{createdAt},
넵. now() 수정할 위치가 어디여야 할지 잘 이해하지 못해서요. 저는 UserMapper.xml 파일 안 insert 구문에서 #{createdAt}을 수정해야 한다고 이해했는데, 생각하신 것과 다르다면 어디에서 수정하는 걸 생각하신지 알려주실 수 있을까요?

2022-10-17 08:28 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +    public void joinUser(@RequestBody JoinUserRequest request) throws Exception {
네! 저희가 joinUser 라는 API를 실행시킬 때, JoinUserRequest타입을 가진 request 라는 객체가 API에 파라미터로 들어오는데, 이 때 @Valid를 활용하고 dto/request/JoinUserRequest 안에서 여러가지 유효성 검사를 활용할 수 있을 것 같습니다. (ex @NotNull)

https://velog.io/@davidko/DTO%EA%B0%80-%EA%B0%90%EC%8B%BC-DTO-%EC%9C%A0%ED%9A%A8%EC%84%B1-%EA%B2%80%EC%82%AC-%EB%B0%A9%EB%B2%95

2022-10-17 08:30 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +            throw new Exception("필수 정보 누락");
다른 상태코드를 반환하기 위해서 @ControllerAdvice와 @ExceptionHandler를 사용해볼 수 있는데, 제 PR을 확인해보시면 제가 구현을 해 놓은 것이 있습니다. (branch는 feature/getProduct 입니다.)

2022-10-17 08:32 UTC, dev-seokho commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    (#{id}, #{email}, #{password}, #{name}, #{phoneNumber}, #{nickname}, #{isAdult}, #{createdAt},
데이터베이스 default 속성 자체를 변경시켜주어야 합니다. 혹시 DB를 터미널에서 사용하고 계신가요? 아니면 GUI 툴을 이용하고 계신게 있으실까요?!

2022-10-17 16:27 UTC, f-lab-jd requested changes
@rogarithm  고생 많으셨습니다~! 리뷰 드린 내용 확인 부탁드립니다 ㅎㅎ 
(cc. @dev-seokho)

2022-10-17 16:27 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +            throw new Exception("필수 정보 누락");
P2 : @rogarithm 이 부분을 CheckedException 을 던지도록 설계하신 이유가 있으실까요~? 
그리고 @dev-seokho 님 리뷰에도 드렸던 내용과 같은 내용입니다! https://github.com/f-lab-edu/sool-dam-a/pull/45#discussion_r996241526

DTO 클래스 검증을 위해 매번 개발자가 if 문을 작성하는 수고를 줄이기 위해 Spring 에서는 `bean validation` 과 `bean validator` 를 제공합니다. 관련해서 한번 알아보시고 @dev-seokho 님께서 이를 적용하신 내용도 @dev-seokho 님 [PR 코드](https://github.com/f-lab-edu/sool-dam-a/pull/45/files#diff-01e01112157f52c50bd4a550fdad91833f4fc045c687efc3e75d5299ae66fddfR23-R39) 리뷰하시면서 함께 봐보시면 좋을 것 같습니다.

2022-10-17 16:27 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/dto/request/JoinUserRequest.java
> +    private String deletedAt;
P2 : @rogarithm 날짜를 표현하기 위해 java 에서 java 8 버전 이후부터 제공해주는 `LocalDateTime` 타입을 활용해보셔도 좋을 것 같습니다! 아주 파워풀한 기능을 제공해줄뿐더러 타입이 명확해져서 개발자의 실수도 줄여줍니다 ㅎㅎ

2022-10-17 16:27 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/dto/response/JoinUserResponse.java
> +    public static JoinUserResponse getResponse(User user) {
P2 : @rogarithm 팩터리 패턴 사용해서 새로운 객체를 만드는 메소드에 대해 @dev-seokho 님 일관성을 맞출 필요가 있습니다. [석호님코드](https://github.com/f-lab-edu/sool-dam-a/pull/45/files#diff-bfff95a4363f13443ba524e04c9d7dea0ea8675761fdeaccd1d3939d5fce8facR15) 이 부분은 당연히 정답이 있는 내용이 아니니, 두분이서 논의해보시면 좋을 것 같습니다!

`java factory pattern naming convention` 이라는 키워드로 검색해보면 여러 사례들이 나오고, [이펙티브 자바](https://multifrontgarden.tistory.com/m/255) 책에 대한 내용도 있네요.

2022-10-17 16:27 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/dto/response/JoinUserResponse.java
> +    private User user;
P3 : @rogarithm @dev-seokho 님께 드렸던 https://github.com/f-lab-edu/sool-dam-a/pull/45/files#r996242935 와 같은 질문입니다. ㅎㅎ JoinUserResponse 클래스(DTO 클래스) 에 Entity 가 그대로 포함되었을때 어떤 장단점이 있을까요~?

2022-10-17 16:27 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +        userMapper.insertUser(request.toUser());
@dev-seokho 님께서 좋은 리뷰 잘 남겨주셨는데요. ㅎㅎ 
요기에서 `암호화` 까지 고려하기에는 너무 큰 이슈라고 생각합니다. 관련해서는 별도 이슈에서 다같이 고민해보시죠~!

2022-10-17 16:27 UTC, f-lab-jd commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    SELECT * FROM user WHERE ID = #{id}
P3: ` SELECT * ` 을 했을때와 `SELECT column1, column2 ...` 처럼 컬렴명을 명시했을때 어떤 차이점이 있을까요~? 
(cc. @dev-seokho)

2022-10-17 16:27 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/api/UserApiTest.java
> +        assertThrows(Exception.class, () -> mockMvc.perform(post("/join")
P5 : https://github.com/f-lab-edu/sool-dam-a/pull/46/files#diff-3adc1dcf5e90394f6078e086c2593c9162f3c03cf58dffda299028a9ca2fe340R69 와 개행 일관성이 맞지 않아 가독성을 해치는것 같습니다 ㅎㅎ 그리고  @dev-seokho 님 작성하신 부분과도 코드스타일이 겹치는 부분인데, 하나의 코드가 병합된다면 되도록이면 하나의 스타일로 가면 좋을 것 같습니다.

2022-10-17 16:27 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/service/UserServiceTest.java
> +        // 회원가입할 사용자 객체 생성
P5 : bdd 에서 사용이 되는 given when then 구조로 테스트코드를 잘 만들어주셨는데요! 
직접 주석에 given when then 주시면 더 가독성이 좋을 것 같습니다~!

2022-10-17 16:27 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/service/UserServiceTest.java
> +        JoinUserRequest request1 = JoinUserRequest.builder()
P5 : @rogarithm  @dev-seokho 님께 드렸던 https://github.com/f-lab-edu/sool-dam-a/pull/45#discussion_r996244308 내용과 같은 내용의 리뷰입니다. 한번 고민해보시면 좋을 것 같습니다 ㅎㅎ

2022-10-18 07:45 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/dto/request/JoinUserRequest.java
> +                .id(this.getId())
넵. 이렇게 바꾸고 연관 있는 곳을 살펴보다 보니, UserServiceTest 클래스 20~39 줄의 userInfoAddedOnDB() 메서드에서 처리가 어려워져서 의견 여쭈어봅니다.

**이전 테스트 실행 방식**
- 테스트는 회원가입 로직 실행 이후 가입한 회원을 id로 찾아 그 값이 (builder 패턴으로 만들 때 하드 코딩으로 넣어줬던) id 값과 같은지를 비교하는 방식으로 실행되었습니다.

**변경 후 테스트 구현에서 생긴 문제**
- id를 하드코딩할 수 있었기에 테스트가 성공할 수 있었지만, 변경 후에는 builder 패턴으로 id를 넣어줄 수 없어 다른 방식으로 가입한 회원을 찾아내야 합니다.

**생각해본 해결 방안**
- 현재 UserService가 DB로부터 회원 정보를 가져올 수 있는 방법은 findUserById 밖에 없는데요. 제 생각에는 UserService 클래스의 (현재 아무것도 반환하지 않는) insertUser() 메서드가 JoinUserResponse 객체를 반환하도록 해서 이 객체로부터 id 값을 가져오는 건 어떨까 생각이 듭니다.
- 다른 필드값을 기준으로 회원을 가져오는 것도 생각해보았지만 중복의 위험이 있다고 생각됩니다.

2022-10-18 07:49 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +    @PostMapping("/join")
넵. 좋은 의견이라고 생각합니다. 같은 클래스 안 모든 api 메서드가 공통으로 쓰는 url 요소를 붙여주는 역할인 것 같네요. 추가하도록 하겠습니다.

2022-10-18 08:05 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +    public void joinUser(@RequestBody JoinUserRequest request) throws Exception {
넵, api 메서드 입력에 @Valid 추가 및 ERD 참고해서 필요한 필드에 @NotNull 추가하겠습니다.

2022-10-18 08:31 UTC, rogarithm commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    (#{id}, #{email}, #{password}, #{name}, #{phoneNumber}, #{nickname}, #{isAdult}, #{createdAt},
터미널에서 사용하고 있습니다. 이렇게 하면 될까요?
1. 로컬 db에서 `DROP TABLE IF EXISTS TABLE_NAME;` 으로 이전에 만든 테이블 삭제
2. 수정해주신 dbdiagram.io에서 새로 ddl 파일 다운로드 후 로컬 db에 적용해 업데이트된 테이블 생성

2022-10-18 08:39 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +            throw new Exception("필수 정보 누락");
유효하지 않은 요청일 경우 `HttpStatus.CREATED` 상태 코드 이외 다른 코드를 반환하려고 했지만 어떤 식으로 구현할지 가닥이 안잡혀서 joinUser 입력이 유효하지 않은 테스트 케이스 구현 방법에 맞춰 CheckedException을 던지도록 설계했습니다.
말씀해주신 내용 알아보고 수정하겠습니다!

2022-10-18 09:24 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/dto/request/JoinUserRequest.java
> +    private String deletedAt;
넵, 적용하겠습니다.

2022-10-18 09:36 UTC, rogarithm commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    SELECT * FROM user WHERE ID = #{id}
- *로 가져오는 경우 모든 컬럼을 가져옵니다. 반면 컬럼명을 명시하면 (모든 컬럼을 다 가져올 수도 있고,) 원하는 컬럼만 명시해서 가져올 수도 있습니다.
- *을 쓰면 이름을 모르는 컬럼도 가져올 수 있습니다. 반면 컬럼명을 명시하는 방식의 경우 가져올 컬럼의 이름을 알아야 합니다.

2022-10-18 09:39 UTC, rogarithm commented on src/test/java/com/flab/sooldama/domain/user/service/UserServiceTest.java
> +        // 회원가입할 사용자 객체 생성
넵, 주석에 추가하겠습니다.

2022-10-18 11:04 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/user/dto/request/JoinUserRequest.java
> +                .id(this.getId())
userInfoAddedOnDB() 테스트코드를 확인해 보았는데요!
해당 테스트코드에서 제가 느껴지는 문제는 2가지라고 생각합니다.
- 유닛 테스트가 아니다.
  - userInfoAddedOnDB() 를 확인해보면 `userService.insertUser(request1);` 라인이 존재하는데요, 이는 말 그대로 request1 이라는 User 객체 자체를 DB에 넣고 있다고 보여집니다. 테스트 코드를 확인해보면, "sehoon@fmail.com" 이라는 유저가 실제로 user 테이블에 생성된다고 보여지고, 이는 UserService - UserMapper - UserMapper.xml - DB 와 같은 Flow로 사실상 서비스와 매퍼를 모두 사용하는 통합테스트에 가깝다고 보여집니다. UserService만을 위한 테스트가 아니라고 생각해요.
- 위와 같은 이유로 테스트코드는 연속해서 동작할 수 없다.
  - 그렇기 때문에 이 테스트 이후에 실제로 application.yml에 등록 돼 있는 mysql db에 해당 데이터가 적재될 것이라고 예상되고, email을 unique 특성으로 넣은 저희의 설계 특성상 "sehoon@fmail.com" 으로 등록된 해당 데이터 를 지워주지 않으면 테스트는 2번 이상 돌아가지 않을 것이라고 생각하는데, 제 생각이 맞나요?
  - 만약 연속적으로 테스트 코드가 동작하도록 하려면, deleteByUserId 라는 쿼리를 만들어서 매 테스트마다 "sehoon@fmail.com"을 삭제해주어야 하지 않을까요?

말씀해주신 해결 방안에서 `현재 UserService가 DB로부터 회원 정보를 가져올 수 있는 방법은 findUserById 밖에 없는데요.` 를 DB를 사용하지 않고 DB에 정말 있는 듯한 목업데이터를 가져올 수 있다면? 이라고 생각해본다면, 제가 제기한 2가지의 문제점이 해결될 것 같다고 생각해요. Mocking 을 도와주는 여러가지들이 있는 것 같은데 확인해보면 어떨까요?!

혹시라도 제 생각이 틀린 생각이라면 언제나 피드백 부탁 드립니다 ㅎㅎ :) !!

2022-10-18 11:04 UTC, dev-seokho commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    (#{id}, #{email}, #{password}, #{name}, #{phoneNumber}, #{nickname}, #{isAdult}, #{createdAt},
만약에 유의미한 데이터가 없는 상황이라면 그냥 아예 테이블 드롭하고 새로 ddl 받아서 적용해주셔도 될 것 같고, 유의미한 데이터가 있는 상황이라면 created_at 이 있는 테이블에 한해서 created_at 의 default 값을 now() 로 변경시켜주는 쿼리를 터미널 안에서 실행시켜주셔야할 것 같습니다 :0

2022-10-18 12:06 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/dto/response/JoinUserResponse.java
> +    private User user;
response dto 변수에서 Entity 필드 값을 빼내려면 일단 Entity로 변경 후 Entity 필드의 getter로 접근해야 하므로 단계가 하나 더 늘어난다고 생각이 듭니다.
`int myId = JoinUserResponse.getResponse(matchedUser).getUser().getId();`
request dto 변수에서는 Entity 필드의 getter를 이용하지 않더라도 바로 접근할 수 있습니다.
```JoinUserRequest request = ...;
int myId = request.getId();```
반면 Entity 클래스가 바뀌더라도 DTO 클래스는 변경되지 않는 장점이 있을 것 같습니다. 만약 Entity에 birthday라는 필드가 추가되었다고 한다면, response dto는 클래스 내부 변경 없이 필드값을 들고 올 수 있지만,
`LocalDateTime myBirthday = JoinUserResponse.getResponse(matchedUser).getUser().getBirthday();`
request dto는 추가된 필드를 자신의 정의에도 추가해주고 난 다음에야 그 필드에 접근할 수 있을 것 같습니다.
```JoinUserRequest request = ...;
LocalDateTime myBirthday = request.getBirthday();```

2022-10-18 14:55 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +            throw new Exception("필수 정보 누락");
@rogarithm UncheckedException vs CheckedException 중에 CheckedException 을 던지도록 설계하신 이유가 궁금합니다~!

2022-10-21 17:05 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/dto/request/JoinUserRequest.java
> +                .id(this.getId())
넵. 테스트 방식을 모의 객체를 이용하도록 변경하겠습니다.

2022-10-21 17:07 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +            throw new Exception("필수 정보 누락");
넵, 말씀해주신 부분 살펴보았습니다. 수정 작업이 다소 길어지는 것 같아 현재까지 리뷰 반영한 내용을 올리고 추가로 작업하려고 합니다.

2022-10-21 17:15 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/dto/request/JoinUserRequest.java
>  public class JoinUserRequest {
넵. @Email 어노테이션을 추가했습니다. 이 어노테이션에서 필터링하지 못하는 케이스가 있는 것 같고, regex는 더 알아보고 추가하겠습니다.

2022-10-21 17:15 UTC, rogarithm commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    (#{id}, #{email}, #{password}, #{name}, #{phoneNumber}, #{nickname}, #{isAdult}, #{createdAt},
이 부분은 알아보았는데 동작 원리는 찾지 못했습니다. 수정사항은 반영했습니다.

2022-10-21 17:15 UTC, rogarithm commented on src/main/resources/mybatis/mapper/UserMapper.xml
> +    (#{id}, #{email}, #{password}, #{name}, #{phoneNumber}, #{nickname}, #{isAdult}, #{createdAt},
넵. 유의미한 데이터가 없어서 새로 ddl 적용해주었습니다.

2022-10-21 17:17 UTC, rogarithm commented on src/test/java/com/flab/sooldama/domain/user/api/UserApiTest.java
> +                JoinUserRequest.builder()
넵. 이 부분은 request dto 수정 후 id 값 넣지 않도록 하고, createdAt 값은 해당 시점에 자동 설정되도록 수정하겠습니다.

2022-10-21 17:19 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +    @ResponseStatus(HttpStatus.CREATED)
넵, 논의해보겠습니다.

2022-10-21 17:22 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +            throw new Exception("필수 정보 누락");
@f-lab-jd 둘 중에 어떤 종류의 예외를 던질지는 고민하지 않았던 것 같고, 그래서 특별히 CheckedException으로 설계한 이유가 없었습니다.

2022-10-21 17:25 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/dto/response/JoinUserResponse.java
> +    public static JoinUserResponse getResponse(User user) {
네, 말씀해주신 참고 자료(이펙티브 자바 아이템 68)도 잘 참고하겠습니다. 메소드 이름을 from으로 바꾸려고 생각하는데, 개인적으로는 static으로 메소드를 사용하기 때문에 클래스이름.메소드이름 방식으로 쓰이게 되어 JoinUserResponse.from이 의미를 알기 더 쉽다고 생각이 들었습니다.

2022-10-21 17:25 UTC, rogarithm commented on src/test/java/com/flab/sooldama/domain/user/api/UserApiTest.java
> +        assertThrows(Exception.class, () -> mockMvc.perform(post("/join")
넵. 수정하겠습니다.

2022-10-21 17:52 UTC, rogarithm commented on src/test/java/com/flab/sooldama/domain/user/service/UserServiceTest.java
> +        JoinUserRequest request1 = JoinUserRequest.builder()
아직 리뷰 반영이 다 되지 않았지만 남은 수정사항 반영에 시간이 오래 걸릴 수 있을 것 같아 먼저 지금까지 반영한 내용에 대해 리뷰 요청드립니다.

리뷰 이외 반영한 사항
- JoinUserRequest에서 deleted_at, updated_at 삭제 (멘토링 시간에 나온 변경사항)
- join api가 response dto를 반환하도록 변경
- 이메일 중복되는 경우 예외 발생하도록 유효성 검사 로직 추가
- 서비스 레이어 테스트를 mock 방식으로 변경
- 새로 추가된 로직을 테스트에 반영

아직 반영하지 않은 사항
- 이메일 유효성 검증 정규 표현식 추가
- name 중복인 경우 유효성 검사 로직 추가
- 유효하지 않은 입력 처리 Exception -> @ControllerAdvice, @ExceptionHandler 활용해서 처리하도록 변경
  - 현재 unchecked exception(DuplicateEmailExistsException, NoSuchUserException)으로 처리해놓은 곳을 변경할 예정입니다.

2022-10-21 17:53 UTC, rogarithm commented
아직 리뷰 반영이 다 되지 않았지만 남은 수정사항 반영에 시간이 오래 걸릴 수 있을 것 같아 먼저 지금까지 반영한 내용에 대해 리뷰 요청드립니다.

리뷰 이외 반영한 사항
- JoinUserRequest에서 deleted_at, updated_at 삭제 (멘토링 시간에 나온 변경사항)
- join api가 response dto를 반환하도록 변경
- 이메일 중복되는 경우 예외 발생하도록 유효성 검사 로직 추가
- 서비스 레이어 테스트를 mock 방식으로 변경
- 새로 추가된 로직을 테스트에 반영

아직 반영하지 않은 사항
- 이메일 유효성 검증 정규 표현식 추가
- name 중복인 경우 유효성 검사 로직 추가
- 유효하지 않은 입력 처리 Exception -> @ControllerAdvice, @ExceptionHandler 활용해서 처리하도록 변경
  - 현재 unchecked exception(DuplicateEmailExistsException, NoSuchUserException)으로 처리해놓은 곳을 변경할 예정입니다.

2022-10-22 13:51 UTC, dev-seokho requested changes

2022-10-22 13:51 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +@RequestMapping("/user")
P2: RequestMapping은 user가 아닌 users로 하는 것이 좀 더 좋아보입니다!! 정답은 없는 내용이지만, 대부분 복수를 사용하고 저도 복수를 사용해서 구현해왔는데 세훈님의 생각은 어떠신가요?!
<img width="795" alt="image" src="https://user-images.githubusercontent.com/56547148/197342309-9ed7ccb0-85e1-4047-9f4d-a9ad87647115.png">

2022-10-22 13:51 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +    @PostMapping("/join")
P4: 이것도 정답이 있는 부분은 아니지만 회원가입의 경우 [POST] /users 로 끝내는 경우가 많았어요.
/users vs /users/join 어떤 중에 전자가 저는 더 좋아보이는데, 세훈님과 JD님의 생각도 듣고싶습니다. cc. @f-lab-jd

2022-10-22 13:51 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/user/dto/response/JoinUserResponse.java
> +    private User user;
P1: DTO와 Entity를 저번 멘토링 시간에 분리하기로 얘기된것으로 알고 있습니다!! 밑에 글로 남겨주신 `아직 반영하지 않은 사항` 에 따로 말씀이 없으셔서, 혹시 잊으셨나 싶어서 여기다가 남겨 놓습니다. :)

2022-10-22 13:55 UTC, dev-seokho commented
@rogarithm 추가적으로 제품조회 기능이 main 브랜치에 merge 되면서, `global/exception`과 `test/resources/application.yml`, `data.sql`, `schema.sql` 등 회원가입을 진행하시면서도 필요한 리소스들이 main 브랜치에 생기게 됐습니다. 아마 global exception 처리를 하시거나 테스트 코드를 사용하실 때, main브랜치를 참고하시거나, main브랜치로 rebase를 해서 확인해보시는것도 괜찮은 방법이 될 것 같아서 여기다가 글을 남겨놓습니다!

2022-10-22 19:20 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/user/dao/UserMapper.java
> +    User findUserByEmail(String email);
P2: findUserById, findUserByEmail 둘 다 User 객체를 Optional로 묶어주어야할 필요성이 있다고 생각합니다. 둘 다 만약 User 객체가 존재하지 않는다면 Service 로직에서 NPE 가 날 것이라고 생각해요.

2022-10-22 19:20 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +        if (userMapper.findUserByEmail(request.getEmail()) != null) {
P2: userMapper 에서 findUserByEmail이 반환하는 User 객체를 Optional로 감싸준다면 이 로직에서 Null 체크를 Optional을 활용해서 구현해볼 수 있을 것 같습니다. :)  이곳과 마찬가지로 UserService의 30번 라인 `if (matchedUser.getClass() == null) {` 부분에도 이를 적용해볼 수 있다고 생각합니다. 세훈님의 생각은 어떠신가요!?

2022-10-22 19:20 UTC, dev-seokho commented on src/test/java/com/flab/sooldama/domain/user/service/UserServiceTest.java
> +@ExtendWith(MockitoExtension.class)
P4: ExtendWith 어노테이션에 대한 주석도 추가해야할 것 같습니다!

2022-10-24 14:47 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +    @PostMapping("/join")
RestfulAPI 를 제공한다고 할때, 정답이 있는 부분입니다. 
RestfulAPI 가 무엇인지는 저희 공부를 해본 경험이 있으니..! 
두분 모두 정답을 아시리라 생각합니다 ㅎㅎ

2022-10-24 14:51 UTC, rogarithm commented on src/test/java/com/flab/sooldama/domain/user/service/UserServiceTest.java
> +@ExtendWith(MockitoExtension.class)
넵. 추가하겠습니다.

2022-10-24 14:54 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/dto/response/JoinUserResponse.java
> +    private User user;
멘토링 때 적은 노트를 확인해 보았는데, 제가 그 부분을 잘 이해하지 못했던 것 같습니다. 석호님 지난 PR 참고해서 반영하겠습니다.

2022-10-24 15:07 UTC, f-lab-jd requested changes
고생하셨습니다! 드린 리뷰 한번 더 확인부탁드립니다.
추가로 UserMapper 에 대한 테스트도 추가해주심 좋을 것 같습니다!

2022-10-24 15:07 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +    public JoinUserResponse insertUser(JoinUserRequest request) {
P3 :  ServiceLayer 의 CRUD 메소드명과 RepositoryLayer 의 CRUD 메소드명이 같을 필요는 없습니다.    
오히려 다르게 하는것이 프로젝트 안에서 명확히 역할을 분리하는 가독성에도 도움을 줍니다.    
그래서 보통 동사형만 변화를 주기도하는데요. (ex. insert => create, find => get ..)   
가장 중요한것은 프로젝트 안에서 일관성이라서 이를 @rogarithm @dev-seokho 두분이서 잘 이야기 나누어서 결정하시면 좋을 것 같습니다.
(https://github.com/f-lab-edu/sool-dam-a/pull/46/files#diff-d0e51ada5f3719d9c5afb9bb5f165415f62c8d31bafdae40f363e40ac61805dbR28 도 해당이 됩니다)

2022-10-24 15:08 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/dto/request/JoinUserRequest.java
>  public class JoinUserRequest {
P5 : @rogarithm 
> 이 어노테이션에서 필터링하지 못하는 케이스

혹시 어떤 케이스가 있나요~~?

2022-10-24 15:10 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/service/UserServiceTest.java
> +        JoinUserRequest request = JoinUserRequest.builder()
P4 : 사용하지 않는 코드는 과감하게 날려버리는 습관을 들이시면 유지보수에 좋습니다 ㅎㅎ (특히나 테스트코드이니..!)

2022-10-24 15:21 UTC, f-lab-jd commented
@rogarithm 


> 이메일 유효성 검증 정규 표현식을 추가했습니다. 표현식의 의미는 이렇습니다.
👍 

> 유효하지 않은 입력 처리 @ControllerAdvice, @ExceptionHandler 활용해서 처리하도록 변경
* 각 도메인에 국한된 예외 클래스에 대해 패키지를 나누신것 좋습니다.
* `ExceptionHandler` 가 있는 `ControllerAdvice` 의 Layer => 말 그대로 Handler 이기 때문에 Controller Layer 로 보기도합니다. 그런데 ControllerAdvice 는 어떤 방식으로 동작하시는지 알고 계시나요~? (관련 없는 질문일 수 있지만) 또, Handler 와 Controller 는 어떤 차이점이 있을까요? 

> UserApi 테스트 추가
* 요 부분은 제가 정확히 잘 이해하지 못한걸수도 있는데요. ㅠㅠ UserApi 클래스 에서 Email 검사로직 테스트가 필요할까요? 

> exception 패키지 안에 있는 클래스 테스트
* exception 클래스 안에 로직이 들어가있다면, 필요합니다. 하지만 지금은 그런 케이스는 없어보입니다.

2022-10-24 16:41 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/dto/request/JoinUserRequest.java
>  public class JoinUserRequest {
@Email은 null인 경우, 빈 문자열("")인 경우도 유효한 값이라고 판단합니다.
@NotNull은 null인 경우만 필터링하고, @NotEmpty는 null인 경우와 빈 문자열인 경우를 필터링합니다.

2022-10-26 03:52 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +@RequestMapping("/user")
@dev-seokho
- 관련 내용을 찾아봤는데, 말씀해주신 대로 복수형으로 쓰는 경우가 대부분이었습니다.
- 반영하려고 하는데 한 가지 의문점이 있습니다. 저는 `POST /users` 에서 `users`는 복수인데 회원 하나를 등록하는 데에 복수형을 쓰는 부분이 이해가 잘 가지 않더라고요.
- 생각해본 것은 'POST api는 등록할 정보를 request body로 보내고, 이 request body 안 user 정보(id, password, email 등)에 따라 회원을 만들게 되므로 `/users/request-body-안-등록할-회원-정보` 와 같은 식으로 본다면 복수형을 쓰더라도 자연스럽게 느껴지는 것 같다' 였습니다. 석호님 생각은 어떠신가요?

2022-10-26 03:58 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +    @PostMapping("/join")
@f-lab-jd @dev-seokho 
Restful API가 잘 기억나지 않아 다시 찾아보고 여기와 연관될 만한 REST 제약 조건을 생각해 보았습니다.
저는 Uniform interface 제약조건 중 identification of resources가 연관있다고 생각이 들었는데요, 각 리소스를 구분할 수 있는 식별자는 유일해야 한다는 조건입니다.
만약 `/users/join`으로 api url을 정한다면, (이를테면) `/user/register`와 같은 url이 같은 기능을 하게 되어 동일한 리소스를 등록하는 식별자가 유일해지지 않을 수 있지 않나 하는 생각을 했습니다. 올바른 접근이 맞는지 궁금합니다.

2022-10-26 09:24 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/dao/UserMapper.java
> +    User findUserByEmail(String email);
@dev-seokho 네, 반영하겠습니다. "Service 로직에서 NPE가 날" 수 있는 상황은 예를 들어
`User userByEmail = userMapper.findUserByEmail(request.getEmail());` 에서 이메일 중복이 아니지만 `userByEmail`가 `null`이 될 수 있는 경우 등을 생각하면 될까요?

2022-10-26 09:26 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +        if (userMapper.findUserByEmail(request.getEmail()) != null) {
네, 적용해볼게요.

2022-10-26 09:41 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/dao/UserMapper.java
> +    JoinUserResponse insertUser(User user);
UserService 테스트에서 회원가입한 User 객체를 가져올 방법을 생각해보다가 response dto를 반환하도록 변경했습니다.

말씀해주신 부분을 확인해보면서 몇 가지 문제점을 발견했습니다.
 - 이전에 insertUser 메소드 반환 타입을 void에서 JoinUserResponse로 바꾸는 과정에서 UserMapper.xml에는 변경 사항을 적용하지 않았습니다. 그래서 UserMapper.java의 insertUser 반환 타입이 다르게 되어 있었지만 확인하지 못했습니다.
-  @SpringBootTest로 DB에 연결하는 통합 테스트를 만들어 insertUser 동작을 확인해보았을 때 반환 타입이 올바르지 않다는 예외가 발생했습니다. 조사해보니 myBatis에서 insert 메소드 반환 타입은 int(insert된 row 갯수) 또는 void이었습니다.
- (만약 dto를 UserMapper 클래스의 insertUser 메소드 반환 타입으로 설정할 수 있다고 하더라도,) dao는 DB와 밀접하게 연관이 되므로 레이어간 데이터 이동을 위한 response dto를 dao에서 반환하는 것은 맞지 않는 것 같습니다.
- 이전에 dto 테스트가 필요한가? 에 대해 이야기했던 적이 있는데, 이런 문제를 방지하기 위해 dto에도 테스트를 짜는 것이 좋다고 생각이 들었습니다.

2022-10-26 09:44 UTC, rogarithm commented on src/test/java/com/flab/sooldama/domain/user/service/UserServiceTest.java
> +        JoinUserRequest request = JoinUserRequest.builder()
@f-lab-jd 
넵. 삭제하겠습니다. 여기서 표시되어 있는 `request`는 테스트에서 사용하는 데이터여서요. 이 테스트에서는 `registeredUser`를 사용하지 않는데, 이걸 삭제하는 걸 의도하신 게 맞을까요?

2022-10-26 10:30 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/user/service/UserServiceTest.java
> +        JoinUserRequest request = JoinUserRequest.builder()
넵 맞습니다~!

2022-10-26 15:06 UTC, f-lab-jd approved these changes
고생하셨습니다 👍

2022-10-26 15:06 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
>      }
P3 : 사용하지 않는 샘플 코드이니, 이번에 아예 삭제해도 좋을 것 같습니다.

2022-10-26 16:03 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
>      }
넵, 반영하겠습니다.

2022-10-26 16:13 UTC, rogarithm commented
@f-lab-jd  님, 아직 반영하지 않은 사항이 있어서요. 일단 공유드리고 적절한 방법으로 처리(추가 PR을 하거나 코멘트로 남기기)하려고 합니다.

1. (**질문**) name 중복인 경우 유효성 검사 로직 추가
  - 고민해보니 서로 다른 사용자이더라도 name이 같은 경우가 발생할 가능성이 종종 있을 것 같다는 생각이 들었습니다. 그래서 name만 가지고 유효성을 검사하는 것이 괜찮은 방법인가 의문이 듭니다.
  - 그대로 구현하는 것이 좋을까요? 아니면 다른 방법으로 하는 것이 좋을까요?

2. ControllerAdvice의 동작 방식과 Handler vs Controller에 대해 알아보기
  - 이 내용은 아직 알아보지 못해서요. 조사 후 코멘트로 남기겠습니다.

3. 이외 회의가 필요한 사항은 정리해서 회의 후 공유드리겠습니다.

2022-10-29 20:27 UTC, dev-seokho approved these changes

2022-10-30 01:57 UTC, merged