[#19] 단일 제품 조회 기능
f-lab-edu/sool-dam-a pull request #60
Opened 2022-11-03 12:01 UTC by dev-seokho

# [#19] 단일 제품 조회 기능

## 작업 내용 (Content)
- 제품 id를 사용해서 단일 제품 조회를 가능하게 합니다.

## 기타 사항 (Etc)
- 

## Merge 전 필요 작업 (Checklist before merge)
- 

## 셀프 체크리스트
- [ ] PR 제목에 PR과 연관된 이슈 번호를 [이슈 번호] 형식으로 추가했나요?
- [ ] 구글 자바 포맷터를 잘 활용했나요?
- [ ] 추가되는 코드에 대해서 테스트 코드가 작성되었나요?
- [ ] 변경된 소스코드가 500라인 이하인가요?
- [ ] 객체지향 생활체조 규칙을 지켰나요?

2022-11-03 14:10 UTC, f-lab-jd requested changes
고생하셨습니다! 리뷰드린 내용 한번 확인 부탁드립니다.

2022-11-03 14:10 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/product/service/ProductService.java
> +        return ProductResponse.builder()
P4 : https://github.com/f-lab-edu/sool-dam-a/pull/60/files#diff-7506e8a2caa06b87b05875d084e7efe53e32be204e4e9eb2cfb8b6a28f4f011eR22 부분과 중복이 되는 Builder 부분인데요. 이 중복을 해결할 수 있는 방법이 있을까요~?

2022-11-03 14:10 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/exception/GlobalExceptionHandler.java
> +	public ResponseEntity<HttpStatus> constraintViolationException(
P1 : ResponseEntity 에서 Generic 으로 받는 타입은 어디에 사용이 될까요~? 
HttpStatus 타입이 적합할까요?!

2022-11-03 14:10 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/domain/product/dao/ProductMapperTest.java
> +        }
P3 : 테스트코드에서 예외처리가 필요할까요~? 
테스트 결과를 검증하는 단계에서의 분기문은 단위테스트에서 불필요해보입니다.

2022-11-04 16:00 UTC, rogarithm requested changes

2022-11-04 16:00 UTC, rogarithm commented on src/test/java/com/flab/sooldama/domain/product/service/ProductServiceTest.java
> +			.thenReturn(Optional.ofNullable(product));
P3: 여기와 184~185번 줄이 같은 클래스 138번 줄과 개행 일관성이 맞지 않는 것 같아요.
로컬 환경에서 확인해보니 줄 길이가 기준을 넘지는 않은 것 같은데 혹시 when절만 이런 식으로 개행하려고 의도하신 걸까요?

2022-11-12 05:17 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/product/service/ProductService.java
> +        return ProductResponse.builder()
DTO 변환을 DTO 객체가 담당하도록하여 보완했습니다 :)

2022-11-12 05:17 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/global/exception/GlobalExceptionHandler.java
> +	public ResponseEntity<HttpStatus> constraintViolationException(
저번 멘토링 시간에서 다뤘던 내용을 적용하였습니다.

2022-11-12 05:17 UTC, dev-seokho commented on src/test/java/com/flab/sooldama/domain/product/dao/ProductMapperTest.java
> +        }
불필요한 예외처리를 삭제했습니다.

2022-11-12 05:17 UTC, dev-seokho commented on src/main/java/com/flab/sooldama/domain/product/api/ProductApi.java
> +    public ResponseEntity<ProductResponse> getProduct(@PathVariable Long productId) {
주석 추가하였습니다.

2022-11-12 05:17 UTC, dev-seokho commented on src/test/java/com/flab/sooldama/domain/product/service/ProductServiceTest.java
> +			.thenReturn(Optional.ofNullable(product));
한줄로 모두 변경하였습니다.

2022-11-12 07:56 UTC, f-lab-jd approved these changes
고생하셨습니다 👍

2022-11-13 05:16 UTC, rogarithm approved these changes

2022-11-13 07:44 UTC, merged