[#7] 로그인 기능
f-lab-edu/sool-dam-a pull request #61
Opened 2022-11-06 10:39 UTC by rogarithm

### [#7] 로그인 기능

## 작업 내용 (Content)
- httpSession을 이용한 로그인 기능 구현 및 테스트 작성

## 기타 사항 (Etc)
1. session attribute 이름을 static final로 선언
- 로그인 관련 session attribute의 이름은 어느 사용자가 로그인하든 항상 동일해야 한다고 생각했습니다.
- 상수값으로 두는 게 좋을 것 같아 `static final`로 정의했습니다.

2. session attribute 이름을 USER_EMAIL로
- 술담아 프로젝트에서는 이메일이 아이디의 역할을 해서 이렇게 했습니다.
- ID를 이름에 넣을 경우, 자동으로 부여되는 long 타입 ID 값과 혼동을 일으킬 수도 있을 것 같습니다.

3. 테스트 코드가 200줄을 넘어가는데 테스트 코드의 경우에도 200줄 이하로 유지하는 게 좋을까요?
- 개선 방안으로 테스트 데이터를 별도의 클래스로 만들어서 import하는 것을 생각해보았습니다.

## 셀프 체크리스트
- [x] PR 제목에 PR과 연관된 이슈 번호를 [이슈 번호] 형식으로 추가했나요?
- [x] 구글 자바 포맷터를 잘 활용했나요?
- [x] 추가되는 코드에 대해서 테스트 코드가 작성되었나요?
- [x] 변경된 소스코드가 500라인 이하인가요?
- [ ] 객체지향 생활체조 규칙을 지켰나요?

2022-11-07 13:43 UTC, f-lab-jd requested changes
👍 고생많으셨습니다!
P1 리뷰 하나만 확인 부탁드립니다~!

2022-11-07 13:43 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +	public ResponseEntity<HttpStatus> loginUser(@RequestBody LoginUserRequest request, HttpSession session) {
P1: https://github.com/f-lab-edu/sool-dam-a/pull/60/files#r1012950427 요기에 석호님께도 드린 리뷰인데요 ㅎㅎ 
 ResponseEntity 에서 Generic 으로 받는 타입은 어디에 사용이 될까요~?

2022-11-07 13:43 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +		if (!request.getPassword().equals(user.getPassword())) {
P5 : 패스워드 암호화는 어떻게하면 좋을지 한번 고민해보시고, 별도 이슈로 생성해서 구현해보시면 좋을 것 같습니다~!
한번 알아보시다가 궁금한점이 있다면 말씀해주세요!

2022-11-10 03:28 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/api/UserApi.java
> +	public ResponseEntity<HttpStatus> loginUser(@RequestBody LoginUserRequest request, HttpSession session) {
멘토링때 알려주신 내용 참고해서 반영했습니다.
참고용으로 여기에도 정리해놓겠습니다.
- ResponseEntity에서 generic으로 받는 타입은 entity body를 나타내는 데 사용됩니다.
- loginUser 메소드는 이미 `ResponseEntity.status(HttpStatus.OK).build()`로 HttpStatus를 반환하고 있습니다.
- 따라서 추가로 body에 HttpStatus를 추가하는 것은 중복이므로 불필요합니다.

2022-11-10 03:28 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +		if (!request.getPassword().equals(user.getPassword())) {
네, 별도 이슈로 생성해서 구현해보겠습니다.

2022-11-12 04:38 UTC, dev-seokho approved these changes

2022-11-12 07:57 UTC, f-lab-jd approved these changes
👍 고생하셨습니다!

2022-11-13 05:14 UTC, merged