[#62] 비밀번호 암호화
f-lab-edu/sool-dam-a pull request #67
Opened 2022-11-19 13:08 UTC by rogarithm

[#62] 비밀번호 암호화

## 작업 내용
- 로그인, 회원가입 기능에 SHA-256 알고리즘을 사용한 비밀번호 암호화 기능 추가
- 테스트 추가 및 기존 테스트에 변경사항 반영

## 셀프 체크리스트
- [x] PR 제목에 PR과 연관된 이슈 번호를 [이슈 번호] 형식으로 추가했나요?
- [x] 구글 자바 포맷터를 잘 활용했나요?
- [x] 추가되는 코드에 대해서 테스트 코드가 작성되었나요?
- [x] 변경된 소스코드가 500라인 이하인가요?
- [x] 객체지향 생활체조 규칙을 지켰나요?

2022-11-20 01:49 UTC, f-lab-jd requested changes
고생하셨습니다! 리뷰드린 내용 한번 확인 부탁드립니다.

2022-11-20 01:49 UTC, f-lab-jd commented on build.gradle
> +					'com.flab.sooldama.domain.user.exception.FailToEncryptPasswordException'
P5: `FailToEncryptPasswordException` 만 exclude 대상으로 등록해야하는 이유가 있으신가요~?

2022-11-20 01:49 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +	public String encryptPassword(String password) {
P3 : 접근제어자를`public` 으로 지정하신이유가 있으신가요~?

2022-11-20 01:49 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +			digest = MessageDigest.getInstance("SHA-256");
P3 : 매직넘버, 매직리터럴은 상수로 관리하는것이 좋습니다.

2022-11-20 01:49 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +		byte hash[] = digest.digest();
P3 : `byte hash[]` 는 자바스타일 array 선언 방식이 아닌데요. 한번 자바스타일로 변경해보셔도 좋을 것 같습니다.

2022-11-20 01:49 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +		StringBuffer result = new StringBuffer();
P3 : `StringBuffer` 를 사용하신 이유는 무엇인가요~? 어떤것과 비교하였고,  어떤 이유로 선택하셨는지 궁금합니다. ㅎㅎ

2022-11-20 01:49 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +		return result.toString();
P5: 요 Line 들의 목적은 무엇인가요? hash 의 각 byte 를 String 에 더하는 과정인데, 가독성을 위해 목적에 맞는 네이밍을 설정하여 함수로 분리해도 좋을 것 같습니다.

2022-11-20 01:49 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/exception/GlobalExceptionHandler.java
> +		return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
P3: 함수명은 handlePasswordNotMatchException 인데, FailToEncryptPasswordException 를 다루고있습니다. 의도하신건가요~?

2022-11-21 11:07 UTC, rogarithm commented on build.gradle
> +					'com.flab.sooldama.domain.user.exception.FailToEncryptPasswordException'
#### FailToEncryptPasswordException(이하 암호화 실패 예외)만 exclude 대상으로 등록한 이유
- jacoco report로 확인해보니 암호화 실패 예외를 exclude 대상으로 등록하지 않을 경우 `FailToEncryptPasswordException(String message)`을 호출하는 테스트가 있어야 합니다. 이 테스트를 작성하려고 했는데 잘 되지 않았습니다.
- 암호화 실패 예외 발생 시 ControllerAdvice에서 처리하는지 확인하는 테스트가 UserApiTest에 있는데, 암호화 실패 예외 테스트가 없더라도 이 예외를 ControllerAdvice가 처리하는 테스트로 충분하지 않을까 생각해서 exlucde 대상으로 등록했습니다.

#### 암호화 실패 예외 테스트하려고 고민해본 것
- UserServiceTest에서 암호화 실패 예외 발생 상황을 테스트하려면 UserService가 이 예외를 발생시키도록 행위를 정의해야겠다고 생각했습니다. 하지만 UserServiceTest에서 UserService는 모의 객체가 아니기 때문에 동작을 임의로 정의할 수 없었습니다.
- 암호화 실패 예외 예외를 발생시키는 테스트용 UserService 클래스를 만드는 방법을 생각해봤습니다. 만약 이렇게 할 경우 추후 UserService 클래스의 동작이 바뀔 경우 테스트용 클래스도 같이 유지보수해야 해서 깔끔한 해결책은 아니라는 생각이 들었습니다.
- UserApiTest에서 모의 객체인 UserService가 NoSuchAlgorithmException를 발생하게 해서 암호화 실패 예외 예외를 발생하도록 하는 방법을 시도해봤습니다. 하지만 NoSuchAlgorithmException이 checked exception이라서 이 방법으로는 테스트가 불가능했습니다.

2022-11-21 11:07 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +			digest = MessageDigest.getInstance("SHA-256");
넵, 변경했습니다.

2022-11-21 11:07 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +		byte hash[] = digest.digest();
넵, 변경했습니다. "자바스타일 array 선언 방식"은 [여기](https://stackoverflow.com/a/129188)를 참고했습니다.

2022-11-21 11:08 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +		StringBuffer result = new StringBuffer();
#### 비교한 것
- StringBuilder와 StringBuffer를 비교했습니다. StringBuilder는 동시성 문제가 있는 반면 연산이 빠르고, StringBuffer는 동시성을 보장해주는 반면 상대적으로 연산이 느립니다.

#### 선택한 이유
- encryptPassword 메소드에서 동시성 문제가 일어날 수 있는지를 고민했는데 답이 나오지 않아서 StringBuffer를 사용했습니다.

#### 고민해본 내용
1. encryptPassword 메소드에서 동시성 문제가 일어날 수 있는지를 다시 고민해봤습니다.
  - 논의 대상인 StringBuffer 타입 변수는 메소드 안에 선언된 지역 변수입니다. 따라서 만약 여러 스레드가 만들어지는 상황이더라도 지역 변수는 메소드 호출 중에만 나타났다가 사라지기 때문에 다른 스레드와 상태가 공유될 가능성이 없습니다.
  - 따라서 StringBuilder로 변경해도 관계 없을 것 같다고 판단해 변경했습니다.

2. 위에서 전개한 논리는 "여러 스레드가 생기는 상황이 발생할 수 있다"는 걸 전제로 합니다. 이 전제가 맞는지 확실히 몰라서 이 부분도 고민해봤습니다.
  - encryptPassword 메소드는 로그인이나 회원가입할 때 실행되는 메소드입니다. 만약 동시에 여러 사람이 로그인을 하거나 회원가입을 하면 여러 스레드가 생기지 않을까 생각했습니다. 하지만 로그인 및 회원가입 과정에 참여하는 UserApi, UserService 등의 클래스는 스프링 빈이므로 싱글톤입니다. 다시 말해 사용자 여러 명의 요청을 동시에 처리하기 위해 UserService 안에 정의된 로직을 사용한다고 해도 동일한 UserService 객체를 사용하게 됩니다.
  - 알아보니 Spring boot에서는 요청마다 스레드를 할당한다고 합니다([참고](https://stackoverflow.com/a/34921727)).

#### 결론
 - 따라서 여러 스레드가 생기는 상황이 발생할 수 있지만 논의 대상인 encryptPassword 메소드 안 StringBuffer 변수는 지역 변수이므로 예상했던 동시성 문제가 생길 가능성이 없어 StringBuilder로 변경해도 무방한 것으로 판단했습니다.

2022-11-21 11:08 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +		return result.toString();
넵, 목적별로 메서드를 분리했습니다.

2022-11-21 11:09 UTC, rogarithm commented on src/main/java/com/flab/sooldama/global/exception/GlobalExceptionHandler.java
> +		return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
아니요, 의도하지 않았습니다. handlePasswordNotMatchException를 복사해서 수정하는 과정에서 메소드 이름 변경을 하지 않았던 것 같습니다. 확인 후 변경했습니다.

2022-11-21 11:19 UTC, rogarithm commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +	public String encryptPassword(String password) {
#### 접근제어자를 public 으로 지정한 이유 
- 비밀번호 암호화 적용 후 UserServiceTest 안의 테스트 중 "암호화된 비밀번호가 요청에 입력한 비밀번호와 다른지를 확인"하기 위한 목적으로 encryptPassword 메소드를 쓰고 있습니다.
- encryptPassword 메소드 접근제어자를 private으로 바꿔봤는데, userService 테스트에서 메소드를 부를 수 없어 public으로 둔 상태였습니다.

#### 고민해본 내용
- 비밀번호 암호화 로직은 가능한 적은 클래스에서 알도록 하는 게 좋을 것 같습니다. 그래서 encryptPassword 메소드에 public보다 제한적인 접근제어자를 지정하기 위한 방법을 고민해봤습니다.
- 첫번째로 테스트에서 암호화 메소드를 직접 부르지 않고 테스트할 수 있도록 변경하려면 어떻게 변경해야할까 고민했습니다. UserService의 loginUser와 insertUser 메소드 반환값으로부터 암호화된 비밀번호값을 얻을 수 있다면 UserServiceTest에서 UserService.encryptPassword를 호출할 필요가 없어져서 메소드 접근제한자를 private으로 바꿀 수 있을 것 같았습니다. 하지만 loginUser는 반환타입이 void이므로 insertUser를 변경해 반환값으로부터 암호화된 비밀번호를 얻을 수 있도록 하더라도 encryptPassword 접근 제한자를 바꿀 수 없다고 생각합니다.
- 두번째로 UserServiceTest에서 실제로 암호화 로직을 이용해 얻은 비밀번호를 사용하는 것이 아니라 임의로 변경한 값을 적용하는 방법을 생각해봤습니다. 이 경우 실제 로직을 쓰지 않으므로 encryptPassword 접근 제한자를 바꿀 수 있을 것 같습니다. 다만 실제 사용되는 로직을 쓰는 것이 아닌 것이 걸립니다.

#### 질문 사항
- 위에서 이야기한 방안을 적용하면 실제로 가능/불가능한지 끝까지 확인해보지 못했는데요. 변경할 점을 확실히 결정할 수 없었기 때문입니다.
- 접근제어자를 public으로 둔 이유를 여쭤보신 이유가 접근제어자를 더 제한적으로 바꾸는 것이 더 낫기 때문일 경우, 접근제한자를 변경할 때 a) 기존 설계의 문제, b) 비밀번호 암호화 로직을 둔 위치의 문제, c) 단위 테스트에서 암호화 로직을 사용하는 방식의 문제(ex. 실제 암호화 로직을 사용할 필요가 없는지), d) 이외의 문제 중 어떤 것을 고려하는 것이 좋을까요?

2022-11-21 16:16 UTC, rogarithm commented
추가로 UserServiceTest에서 쓰는 테스트 데이터를 한 곳에서 생성하도록 리팩토링했습니다.
기존에는 메소드마다 테스트 데이터를 따로 만들었는데요. 살펴보니 굳이 따로 만들 필요가 없었고, 한 번에 여러 테스트를 수정할 때 이해하기 좀 더 쉽도록 이렇게 변경했습니다.

2022-11-22 12:39 UTC, f-lab-jd commented on build.gradle
> +					'com.flab.sooldama.domain.user.exception.FailToEncryptPasswordException'
> 암호화 실패 예외 발생 시 ControllerAdvice에서 처리하는지 확인하는 테스트가 UserApiTest에 있는데, 암호화 실패 예외 테스트가 없더라도 이 예외를 ControllerAdvice가 처리하는 테스트로 충분하지 않을까 생각해서 exlucde 대상으로 등록했습니다.

프로젝트의 모든면에서 일관성을 유지하는게 중요합니다. 해당 예외는 없애는 방향으로 진행하는게 장기적인 유지보수 관점에서 좋습니다. 

> UserApiTest에서 모의 객체인 UserService가 NoSuchAlgorithmException를 발생하게 해서 암호화 실패 예외 예외를 발생하도록 하는 방법을 시도해봤습니다. 하지만 NoSuchAlgorithmException이 checked exception이라서 이 방법으로는 테스트가 불가능했습니다.

`doThrow()` 를 사용하셔서 체크드 익셉션이라 실패하신 것 같은데요. `doAnswer()` 를 활용하는 방법도 있습니다. (하지만 UserService가 NoSuchAlgorithmException 을 발생시킨다고 해도.. 의도하신 테스트는 되지 않을 것 같네요.

2022-11-22 12:44 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/domain/user/service/UserService.java
> +	public String encryptPassword(String password) {
패키지, 접근제어자 등을 사용해야하는 이유가 무엇일까요~? 여러가지가 이유가 있지만 두개 모두 유지보수에 큰 영향을 미치기 때문인데요. 
`테스트 코드를 위해` public 으로 해당 메소드를 열어두는것은 불필요해보입니다.
private method 를 junit 에서 테스트할 수 있는 방법이 없을지 한번 검색해보시면 좋을 것 같습니다.

2022-11-22 12:47 UTC, f-lab-jd reviewed
고생하셨습니다! 
1. 테스트코드 일관된 exclude
2. 접근제어자 
두개만 한번 더 확인해보심 좋을 것 같습니다!

2022-11-22 17:09 UTC, rogarithm commented
- 테스트코드 일관된 exclude
  - 해당 예외 및 관련 코드 삭제했습니다.
  - build.gradle에서 jacoco exclude 설정을 되돌렸습니다.
- 접근제어자
  - private으로 변경 후 리플렉션을 활용하여 테스트하도록 변경했습니다.

2022-11-23 11:30 UTC, f-lab-jd approved these changes

2022-11-23 12:05 UTC, merged