[#74] Redis 연동
f-lab-edu/sool-dam-a pull request #75
Opened 2022-12-01 10:06 UTC by rogarithm

### [#74] Redis 연동

## 작업 내용 (Content)
- 세션 저장소로 Redis를 사용하도록 변경했습니다.
- 테스트 시 Embedded Redis를 사용하도록 변경했습니다.
- 불필요한 애플리케이션의 main() 메소드에 대한 테스트를 지웠습니다.

## 셀프 체크리스트
- [x] PR 제목에 PR과 연관된 이슈 번호를 [이슈 번호] 형식으로 추가했나요?
- [x] 구글 자바 포맷터를 잘 활용했나요?
- [x] 추가되는 코드에 대해서 테스트 코드가 작성되었나요?
- [x] 변경된 소스코드가 500라인 이하인가요?
- [ ] 객체지향 생활체조 규칙을 지켰나요?

2022-12-03 01:51 UTC, f-lab-jd requested changes
고생하셨습니다. 리뷰 드린 내용 한번 확인 부탁드립니다.

2022-12-03 01:51 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/config/RedisConfig.java
> +@EnableRedisHttpSession(maxInactiveIntervalInSeconds = RedisConfig.EXPIRE_TIME)
P5: 저희가 기존에 정했던 문화에 따라 처음 등장한 어노테이션이 어떤 동작을 포함하고 있는지 주석으로 남겨주시면 좋을 것 같습니다.

2022-12-03 01:51 UTC, f-lab-jd commented on src/main/java/com/flab/sooldama/global/config/RedisConfig.java
> +	static final int EXPIRE_TIME = 60;
P5 : 60초로 하신 이유가 있으신가요~?

2022-12-03 01:51 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/global/config/EmbeddedRedisConfig.java
> +@PropertySource(value = "classpath:application-test.yml", factory = YamlPropertySourceFactory.class)
P3 : 마찬가지로 주석이 필요합니다. 그리고 PropertySource 를 사용하여 yml 파일을 명시한 이유는 무엇인가요?
Profile 을 통해서 해결할 수 는 없을까요?

2022-12-03 01:51 UTC, f-lab-jd commented on src/test/java/com/flab/sooldama/global/config/EmbeddedRedisConfig.java
> +		int redisPort = isRedisRunning() ? findAvailablePort() : port;
P3 : port 를 고정하지 않고 availablePort 를 찾아서 할당하는 이유는 무엇인가요?

2022-12-03 02:17 UTC, rogarithm commented on src/test/java/com/flab/sooldama/global/config/EmbeddedRedisConfig.java
> +		int redisPort = isRedisRunning() ? findAvailablePort() : port;
port가 고정되어 있을 경우, 스프링 컨텍스트를 띄우는 테스트 여러 개를 한꺼번에 실행했을 때 문제가 생깁니다. 한 테스트에서 port에 embedded redis server를 할당한 상태에서 새로운 테스트에서 동일한 port에 embedded redis server를 만들 수 없어 실패합니다. 그래서 스프링 컨텍스트를 띄우는 테스트마다 port를 할당했습니다.

2022-12-03 02:19 UTC, f-lab-jd approved these changes

2022-12-03 02:25 UTC, rogarithm commented on src/test/java/com/flab/sooldama/global/config/EmbeddedRedisConfig.java
> +@PropertySource(value = "classpath:application-test.yml", factory = YamlPropertySourceFactory.class)
app-test.yml 안에 정의한 spring.redis.host와 spring.redis.port를 EmbeddedRedisConfig 클래스에서 사용합니다. 이 두 값을 가져오기 위해 @<!-- -->PropertySource를 사용했습니다. 테스트해보니 @<!-- -->Profile과 @<!-- -->ActiveProfile로도 주입 가능한 것을 확인했습니다. 주석 추가하고 수정해서 반영하겠습니다.

2022-12-03 02:37 UTC, rogarithm commented on src/main/java/com/flab/sooldama/global/config/RedisConfig.java
> +	static final int EXPIRE_TIME = 60;
기본값은 30분이고, [스프링 공식 문서](https://docs.spring.io/spring-session/docs/2.2.x/reference/html/api.html#api-redisindexedsessionrepository-expiration)에 따르면 만료 시간은 이 값에 5분이 추가되어 35분이 걸립니다. 기본값으로는 세션 만료를 빠르게 확인할 수 없어서 만료 시간이 6분이 되도록 바꿨습니다.

2022-12-03 02:38 UTC, rogarithm commented on src/main/java/com/flab/sooldama/global/config/RedisConfig.java
> +@EnableRedisHttpSession(maxInactiveIntervalInSeconds = RedisConfig.EXPIRE_TIME)
넵, 반영하겠습니다.

2022-12-03 07:50 UTC, rogarithm commented
말씀해주신 내용을 반영해 커밋 추가했습니다. 리뷰 부탁드립니다.

2022-12-04 01:15 UTC, f-lab-jd approved these changes
👍

2022-12-04 14:32 UTC, merged